### PR TITLE
Update go modules, actions and Rockylinux image

### PR DESCRIPTION
**Pull request by chimanjain**
# Description

* Updated go modules
* Updated github actions
* Updated Rockylinux image

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/885 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- Sanity Test
 
Screenshot 2023-09-06 121734

Screenshot 2023-09-06 151759

Screenshot 2023-09-06 154300

Screenshot 2023-09-06 155115

Screenshot 2023-09-06 155128

Screenshot 2023-09-06 155143

### CODE REVIEW

**Review by prablr79 — APPROVED** [review]
lgtm

**Review by shefali-malhotra — APPROVED** [review]
LGTM

**Comment by prablr79** [comment]
can you check the Lint issue 
image

**Comment by chimanjain** [comment]
> can you check the Lint issue image

@prablr79 These warnings/errors are shown by golangci-lint. We have to fix them but as of now they are not hindering the intended functionality of driver. Most of them are formatting/linting fixes.

**Pull request merged**
