### PR TITLE
Support for K8s 1.16 and Helm 3

### PR DESCRIPTION
**Pull request by sudo-bmitch**
The 1.14 templates with Helm 2 support needed several changes to support a 1.16 Kubernetes environment and Helm v3.  These were mostly Kubernetes API changes.

We also removed the `KubeletPluginsWatcher=true` feature-gate from our environment since that went GA and is no longer a valid gate. That change to the documentation is not capture in this PR.

Signed-off-by: Brandon Mitchell <git@bmitch.net>

### CODE REVIEW

**Comment by zackzhenzhang** [comment]
@sudo-bmitch , thank you for showing interest in the project. We will evaluate your request for future releases.

**Comment by haisumb** [comment]
@zackzhenzhang Any update on this?

**Comment by astripei70** [comment]
@haisumb K8s 1.16 support is coming up in a few days.

**Comment by prablr79** [comment]
This is old PR, hence closing this PR.

**Pull request closed without merging**
