### PR TITLE
K8s - 126 Changes in CSI Powerscale

### PR DESCRIPTION
**Pull request by rajkumar-palani**
# Description
Changes related to installing CSI Power scale Driver on K8s-1.26 version

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/597 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Driver Installation and PVC Creation - Sanity

Driver Installation:
image

Nodes:
image

Storage Class:
image

PVC:
image

PVC in OneFS:
image

- [x] Snapshot - Sanity

image

Snapshot in OneFS:
image

- [x] PVC From Snapshot - Sanity

image

image

### CODE REVIEW

**Review by nitesh3108 — COMMENTED** [review]
Hope you have installed Driver and covered sanity.

**Review by prablr79 — APPROVED** [review]
lgtm

**Review by shefali-malhotra — COMMENTED** [review]
Please revisit the Checklist.

**Review by shefali-malhotra — APPROVED** [review]
LGTM

**Pull request merged**
